Develop
pmmson/webstore pull request #4
Opened 2019-11-24 16:54 UTC by pmmson

2019-11-26 11:46 UTC, Infarh requested changes

2019-11-26 11:46 UTC, Infarh commented on WebStore/Views/Home/Index.cshtml
> +                }
Так как у Вас `Partial/_FeaturesItems` имеет модель `IEnumerable<WebStore.Models.Product.ProductViewModel>`, то надо туда передавать не отдельно каждый товар, а все товары скопом:

```
<partial name="Partial/_FeaturesItems" model="@Model.Products" />
```

2019-11-26 11:46 UTC, Infarh commented on WebStore/Controllers/HomeController.cs
> -        public IActionResult ProductDetails() => View();
Выше здесь - метод `Index()` у Вас вызывается неправильно. Представление действия Index имеет модель, которую Вы не передаёте. 
Вызывать надо так:

```
public IActionResult Index([FromServices] IProductData ProductData) => 
    View(new CatalogViewModel
    {
        Products = ProductData.GetProducts(new ProductFilter()).Select(p => new ProductViewModel
        {
            Id = p.Id,
            Name = p.Name,
            Price = p.Price,
            Order = p.Order,
            ImageUrl = p.ImageUrl
        })
    });
```

2019-11-28 03:33 UTC, pmmson commented on WebStore/Views/Home/Index.cshtml
> +                }
Увидел! Спасибо

2019-11-28 13:08 UTC, pmmson commented on WebStore/Controllers/HomeController.cs
> -        public IActionResult ProductDetails() => View();
Да( догадывался, но не дошел...
Спасибо, Павел!
Есть вопрос: не могли бы пояснить назначение атрибута FormServices (без него сайт не стартует)
в каких ситуациях он применяется?
если пропустил на вебинаре информацию об этом - просто дайте мне знать я пересмотрю :)

2019-12-01 05:01 UTC, merged